export const HOLIDAYS = [
  {
    id: "mid-autumn-2026",
    name: "中秋假期",
    type: "short",
    countryOrRegion: "中国大陆",
    startDate: "2026-09-25",
    endDate: "2026-09-27",
    isBuiltin: true,
    isRecommended: true,
    priority: 84,
    reason: "三天短假适合江南、海滨和近程东亚直飞目的地，可提前观察周五出发和错峰返程价格。",
    flexBefore: 1,
    flexAfter: 1
  },
  {
    id: "national-day-2026",
    name: "国庆假期",
    type: "long",
    countryOrRegion: "中国大陆",
    startDate: "2026-10-01",
    endDate: "2026-10-07",
    isBuiltin: true,
    isRecommended: true,
    priority: 98,
    reason: "长假适合监控国内长线和东亚、东南亚国际航线，可用前后浮动日期错峰。",
    flexBefore: 2,
    flexAfter: 2
  },
  {
    id: "new-year-2027",
    name: "元旦假期",
    type: "short",
    countryOrRegion: "中国大陆",
    startDate: "2027-01-01",
    endDate: "2027-01-03",
    isBuiltin: true,
    isRecommended: true,
    priority: 76,
    reason: "短假适合直飞密度高、飞行时间短的城市，重点监控早去晚回。",
    flexBefore: 1,
    flexAfter: 1
  },
  {
    id: "spring-festival-2027",
    name: "春节假期",
    type: "winter-long",
    countryOrRegion: "中国大陆",
    startDate: "2027-02-06",
    endDate: "2027-02-13",
    isBuiltin: true,
    isRecommended: true,
    priority: 100,
    reason: "全年最适合提前监控的假期之一，温暖海岛、雪景和长线人文目的地都值得关注。",
    flexBefore: 3,
    flexAfter: 3
  },
  {
    id: "qingming-2027",
    name: "清明假期",
    type: "short",
    countryOrRegion: "中国大陆",
    startDate: "2027-04-03",
    endDate: "2027-04-05",
    isBuiltin: true,
    isRecommended: true,
    priority: 68,
    reason: "短假更适合国内人文城市、江南和近程东亚直飞目的地。",
    flexBefore: 1,
    flexAfter: 1
  },
  {
    id: "labor-day-2027",
    name: "劳动节假期",
    type: "medium",
    countryOrRegion: "中国大陆",
    startDate: "2027-05-01",
    endDate: "2027-05-05",
    isBuiltin: true,
    isRecommended: true,
    priority: 88,
    reason: "五天假期适合国内自然风景、历史人文和周边国际航线组合监控。",
    flexBefore: 2,
    flexAfter: 2
  },
  {
    id: "dragon-boat-2027",
    name: "端午假期",
    type: "short",
    countryOrRegion: "中国大陆",
    startDate: "2027-06-07",
    endDate: "2027-06-09",
    isBuiltin: true,
    isRecommended: true,
    priority: 64,
    reason: "短假适合国内短线、海滨城市和飞行时间较短的国际目的地。",
    flexBefore: 1,
    flexAfter: 1
  }
];

export const DESTINATIONS = [
  {
    id: "beijing",
    name: "北京",
    countryOrRegion: "中国大陆",
    isDomestic: true,
    airportCodes: ["PEK", "PKX"],
    tags: ["历史人文", "博物馆", "短假"],
    bestSeasons: ["春季", "秋季"],
    travelValueNote: "历史人文密度高，航班多，适合短假直飞。",
    visaNote: "无需签证",
    isSystemRecommended: true,
    priority: 82,
    reason: "上海出发航班密集，历史人文强，短假也容易成行。",
    recommendedHolidayTypes: ["short", "medium"],
    recommendedStrategyTypes: ["direct"],
    baseDirectPrice: 980,
    baseTransferPrice: 1280,
    valueScores: { nature: 45, culture: 96, convenience: 95, visa: 100 }
  },
  {
    id: "xian",
    name: "西安",
    countryOrRegion: "中国大陆",
    isDomestic: true,
    airportCodes: ["XIY"],
    tags: ["历史人文", "古城", "美食"],
    bestSeasons: ["春季", "秋季"],
    travelValueNote: "历史遗产集中，适合三到五天行程。",
    visaNote: "无需签证",
    isSystemRecommended: true,
    priority: 84,
    reason: "历史人文价值高，航程适中，常适合节假日监控。",
    recommendedHolidayTypes: ["short", "medium", "long"],
    recommendedStrategyTypes: ["direct"],
    baseDirectPrice: 1100,
    baseTransferPrice: 1380,
    valueScores: { nature: 50, culture: 97, convenience: 88, visa: 100 }
  },
  {
    id: "guilin",
    name: "桂林",
    countryOrRegion: "中国大陆",
    isDomestic: true,
    airportCodes: ["KWL"],
    tags: ["自然风景", "山水", "亲子"],
    bestSeasons: ["春季", "秋季"],
    travelValueNote: "山水目的地代表，适合四到六天慢旅行。",
    visaNote: "无需签证",
    isSystemRecommended: true,
    priority: 80,
    reason: "自然风景辨识度高，适合五一、国庆和错峰长周末。",
    recommendedHolidayTypes: ["medium", "long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 1280,
    baseTransferPrice: 1080,
    valueScores: { nature: 95, culture: 66, convenience: 78, visa: 100 }
  },
  {
    id: "lijiang-dali",
    name: "丽江 / 大理",
    countryOrRegion: "中国大陆",
    isDomestic: true,
    airportCodes: ["LJG", "DLU"],
    tags: ["自然风景", "古城", "慢旅行"],
    bestSeasons: ["春季", "秋季", "冬季"],
    travelValueNote: "自然景观和人文古城兼具，适合长假。",
    visaNote: "无需签证",
    isSystemRecommended: true,
    priority: 86,
    reason: "兼顾自然和人文，上海出发常有直飞或昆明中转方案。",
    recommendedHolidayTypes: ["long", "winter-long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 1780,
    baseTransferPrice: 1480,
    valueScores: { nature: 93, culture: 82, convenience: 72, visa: 100 }
  },
  {
    id: "sanya",
    name: "三亚 / 海口",
    countryOrRegion: "中国大陆",
    isDomestic: true,
    airportCodes: ["SYX", "HAK"],
    tags: ["海岛", "自然风景", "亲子"],
    bestSeasons: ["冬季", "春季"],
    travelValueNote: "国内避寒海岛，春节价格波动大，值得提前监控。",
    visaNote: "无需签证",
    isSystemRecommended: true,
    priority: 78,
    reason: "春节和冬季需求高，适合监控低价窗口。",
    recommendedHolidayTypes: ["winter-long", "long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 2100,
    baseTransferPrice: 1680,
    valueScores: { nature: 86, culture: 48, convenience: 82, visa: 100 }
  },
  {
    id: "tokyo",
    name: "东京",
    countryOrRegion: "日本",
    isDomestic: false,
    airportCodes: ["NRT", "HND"],
    tags: ["历史人文", "城市", "自然延展"],
    bestSeasons: ["春季", "秋季", "冬季"],
    travelValueNote: "城市体验丰富，周边自然和历史目的地延展性强。",
    visaNote: "通常需要日本签证",
    isSystemRecommended: true,
    priority: 92,
    reason: "上海直飞丰富，价格波动频繁，适合长期监控。",
    recommendedHolidayTypes: ["medium", "long", "winter-long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 2300,
    baseTransferPrice: 1750,
    valueScores: { nature: 76, culture: 88, convenience: 91, visa: 62 }
  },
  {
    id: "osaka-kyoto",
    name: "大阪 / 京都",
    countryOrRegion: "日本",
    isDomestic: false,
    airportCodes: ["KIX", "ITM"],
    tags: ["历史人文", "古都", "美食"],
    bestSeasons: ["春季", "秋季", "冬季"],
    travelValueNote: "京都历史人文强，大阪交通和航班选择丰富。",
    visaNote: "通常需要日本签证",
    isSystemRecommended: true,
    priority: 94,
    reason: "历史人文匹配度高，上海出发直飞与中转都值得分别监控。",
    recommendedHolidayTypes: ["medium", "long", "winter-long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 2200,
    baseTransferPrice: 1680,
    valueScores: { nature: 68, culture: 96, convenience: 88, visa: 62 }
  },
  {
    id: "sapporo",
    name: "札幌",
    countryOrRegion: "日本",
    isDomestic: false,
    airportCodes: ["CTS"],
    tags: ["雪景", "自然风景", "温泉"],
    bestSeasons: ["冬季", "夏季"],
    travelValueNote: "冬季雪景和温泉价值高，春节适配度强。",
    visaNote: "通常需要日本签证",
    isSystemRecommended: true,
    priority: 88,
    reason: "春节和冬季旅行价值高，中转常能拉低价格。",
    recommendedHolidayTypes: ["winter-long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 3100,
    baseTransferPrice: 2350,
    valueScores: { nature: 94, culture: 65, convenience: 70, visa: 62 }
  },
  {
    id: "seoul",
    name: "首尔",
    countryOrRegion: "韩国",
    isDomestic: false,
    airportCodes: ["ICN", "GMP"],
    tags: ["短途", "历史人文", "美食"],
    bestSeasons: ["春季", "秋季", "冬季"],
    travelValueNote: "短途国际航线，适合三到五天行程。",
    visaNote: "需按当期政策确认入境要求",
    isSystemRecommended: true,
    priority: 87,
    reason: "飞行时间短，直飞多，短假和中假都适合监控。",
    recommendedHolidayTypes: ["short", "medium", "long"],
    recommendedStrategyTypes: ["direct"],
    baseDirectPrice: 1600,
    baseTransferPrice: 1780,
    valueScores: { nature: 54, culture: 82, convenience: 91, visa: 70 }
  },
  {
    id: "bangkok",
    name: "曼谷",
    countryOrRegion: "泰国",
    isDomestic: false,
    airportCodes: ["BKK", "DMK"],
    tags: ["历史人文", "美食", "性价比"],
    bestSeasons: ["冬季", "春季"],
    travelValueNote: "城市、寺庙、美食和周边路线丰富，常有价格机会。",
    visaNote: "需按当期政策确认入境要求",
    isSystemRecommended: true,
    priority: 91,
    reason: "东南亚性价比代表，直飞和中转都值得监控。",
    recommendedHolidayTypes: ["long", "winter-long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 2400,
    baseTransferPrice: 1850,
    valueScores: { nature: 66, culture: 84, convenience: 82, visa: 78 }
  },
  {
    id: "chiang-mai",
    name: "清迈",
    countryOrRegion: "泰国",
    isDomestic: false,
    airportCodes: ["CNX"],
    tags: ["自然风景", "历史人文", "慢旅行"],
    bestSeasons: ["冬季"],
    travelValueNote: "山地、古城和慢旅行氛围突出，适合春节错峰。",
    visaNote: "需按当期政策确认入境要求",
    isSystemRecommended: true,
    priority: 83,
    reason: "自然和人文均衡，中转价格常比直飞更有优势。",
    recommendedHolidayTypes: ["winter-long", "long"],
    recommendedStrategyTypes: ["transfer"],
    baseDirectPrice: 3100,
    baseTransferPrice: 2100,
    valueScores: { nature: 84, culture: 82, convenience: 68, visa: 78 }
  },
  {
    id: "danang",
    name: "岘港",
    countryOrRegion: "越南",
    isDomestic: false,
    airportCodes: ["DAD"],
    tags: ["海滨", "历史人文", "性价比"],
    bestSeasons: ["春季", "冬季"],
    travelValueNote: "海滨、会安和顺化组合，兼顾自然与人文。",
    visaNote: "需按当期政策确认入境要求",
    isSystemRecommended: true,
    priority: 85,
    reason: "价格潜力好，适合长假中转策略监控。",
    recommendedHolidayTypes: ["long", "winter-long"],
    recommendedStrategyTypes: ["transfer"],
    baseDirectPrice: 2800,
    baseTransferPrice: 1900,
    valueScores: { nature: 82, culture: 78, convenience: 66, visa: 70 }
  },
  {
    id: "penang",
    name: "槟城",
    countryOrRegion: "马来西亚",
    isDomestic: false,
    airportCodes: ["PEN"],
    tags: ["历史人文", "美食", "海滨"],
    bestSeasons: ["冬季", "春季"],
    travelValueNote: "乔治市人文和美食辨识度强，适合慢旅行。",
    visaNote: "需按当期政策确认入境要求",
    isSystemRecommended: true,
    priority: 79,
    reason: "历史人文和性价比兼具，中转方案值得监控。",
    recommendedHolidayTypes: ["long", "winter-long"],
    recommendedStrategyTypes: ["transfer"],
    baseDirectPrice: 3000,
    baseTransferPrice: 2050,
    valueScores: { nature: 62, culture: 88, convenience: 64, visa: 76 }
  },
  {
    id: "chengdu",
    name: "成都",
    countryOrRegion: "中国大陆",
    isDomestic: true,
    airportCodes: ["CTU", "TFU"],
    tags: ["历史人文", "美食", "自然延展"],
    bestSeasons: ["春季", "秋季", "冬季"],
    travelValueNote: "城市人文和周边自然目的地兼具，适合三到五天行程。",
    visaNote: "无需签证",
    isSystemRecommended: true,
    priority: 84,
    reason: "上海出发航班丰富，价格弹性好，适合短假和中长假监控。",
    recommendedHolidayTypes: ["short", "medium", "long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 1320,
    baseTransferPrice: 1180,
    valueScores: { nature: 78, culture: 86, convenience: 86, visa: 100 }
  },
  {
    id: "zhangjiajie",
    name: "张家界",
    countryOrRegion: "中国大陆",
    isDomestic: true,
    airportCodes: ["DYG"],
    tags: ["自然风景", "山川", "长假"],
    bestSeasons: ["春季", "秋季"],
    travelValueNote: "自然景观辨识度极高，适合五一、国庆和错峰长周末。",
    visaNote: "无需签证",
    isSystemRecommended: true,
    priority: 81,
    reason: "自然风景强，但直飞选择有限，中转策略值得单独监控。",
    recommendedHolidayTypes: ["medium", "long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 1500,
    baseTransferPrice: 1250,
    valueScores: { nature: 98, culture: 58, convenience: 66, visa: 100 }
  },
  {
    id: "xiamen",
    name: "厦门",
    countryOrRegion: "中国大陆",
    isDomestic: true,
    airportCodes: ["XMN"],
    tags: ["海滨", "历史人文", "短假"],
    bestSeasons: ["春季", "秋季", "冬季"],
    travelValueNote: "海滨、街区和人文体验集中，短假也容易成行。",
    visaNote: "无需签证",
    isSystemRecommended: true,
    priority: 78,
    reason: "上海出发直飞密度高，适合元旦、清明、端午等短假。",
    recommendedHolidayTypes: ["short", "medium"],
    recommendedStrategyTypes: ["direct"],
    baseDirectPrice: 960,
    baseTransferPrice: 1180,
    valueScores: { nature: 72, culture: 78, convenience: 90, visa: 100 }
  },
  {
    id: "hong-kong",
    name: "香港",
    countryOrRegion: "中国香港",
    isDomestic: false,
    airportCodes: ["HKG"],
    tags: ["城市", "历史人文", "转机便利"],
    bestSeasons: ["秋季", "冬季", "春季"],
    travelValueNote: "城市体验、离岛和转机便利兼具，短假友好。",
    visaNote: "需确认港澳通行证及签注",
    isSystemRecommended: true,
    priority: 83,
    reason: "上海直飞多，价格波动明显，也适合作为国际中转观察点。",
    recommendedHolidayTypes: ["short", "medium", "long"],
    recommendedStrategyTypes: ["direct"],
    baseDirectPrice: 1500,
    baseTransferPrice: 1700,
    valueScores: { nature: 58, culture: 80, convenience: 94, visa: 82 }
  },
  {
    id: "taipei",
    name: "台北",
    countryOrRegion: "中国台湾",
    isDomestic: false,
    airportCodes: ["TPE", "TSA"],
    tags: ["历史人文", "美食", "自然延展"],
    bestSeasons: ["春季", "秋季", "冬季"],
    travelValueNote: "城市人文、美食和周边山海线路丰富，适合短中假期。",
    visaNote: "需确认当期入境与证件政策",
    isSystemRecommended: true,
    priority: 82,
    reason: "航程短、旅行价值高，适合和首尔、香港一起做短假对比。",
    recommendedHolidayTypes: ["short", "medium"],
    recommendedStrategyTypes: ["direct"],
    baseDirectPrice: 1750,
    baseTransferPrice: 1900,
    valueScores: { nature: 74, culture: 84, convenience: 84, visa: 68 }
  },
  {
    id: "fukuoka",
    name: "福冈",
    countryOrRegion: "日本",
    isDomestic: false,
    airportCodes: ["FUK"],
    tags: ["短途国际", "美食", "温泉延展"],
    bestSeasons: ["春季", "秋季", "冬季"],
    travelValueNote: "九州门户，适合短假城市旅行和温泉延展。",
    visaNote: "通常需要日本签证",
    isSystemRecommended: true,
    priority: 80,
    reason: "航程较短，中转和直飞价差值得观察，是日本线的低价候选。",
    recommendedHolidayTypes: ["short", "medium", "long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 2050,
    baseTransferPrice: 1650,
    valueScores: { nature: 72, culture: 80, convenience: 80, visa: 62 }
  },
  {
    id: "singapore",
    name: "新加坡",
    countryOrRegion: "新加坡",
    isDomestic: false,
    airportCodes: ["SIN"],
    tags: ["城市", "亲子", "转机便利"],
    bestSeasons: ["全年"],
    travelValueNote: "城市秩序、亲子设施和区域中转便利度高。",
    visaNote: "需确认当期入境政策",
    isSystemRecommended: true,
    priority: 77,
    reason: "直飞稳定但价格偏高，适合和东南亚中转方案分开监控。",
    recommendedHolidayTypes: ["medium", "long", "winter-long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 3000,
    baseTransferPrice: 2350,
    valueScores: { nature: 54, culture: 76, convenience: 92, visa: 72 }
  },
  {
    id: "hanoi",
    name: "河内",
    countryOrRegion: "越南",
    isDomestic: false,
    airportCodes: ["HAN"],
    tags: ["历史人文", "美食", "性价比"],
    bestSeasons: ["秋季", "冬季", "春季"],
    travelValueNote: "老城、人文和周边自然延展兼具，适合低预算长周末。",
    visaNote: "需确认当期入境政策",
    isSystemRecommended: true,
    priority: 78,
    reason: "东南亚人文线低价潜力好，中转方案经常有价格机会。",
    recommendedHolidayTypes: ["medium", "long", "winter-long"],
    recommendedStrategyTypes: ["direct", "transfer"],
    baseDirectPrice: 2450,
    baseTransferPrice: 1750,
    valueScores: { nature: 70, culture: 86, convenience: 68, visa: 70 }
  }
];

export const RECOMMENDATION_PRESETS = [
  {
    id: "preset-mid-autumn-short-culture",
    name: "中秋近程人文与海滨线",
    holidayId: "mid-autumn-2026",
    destinationIds: ["xiamen", "fukuoka", "taipei"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 1900,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct", "transfer"],
    tags: ["中秋", "短假", "海滨人文"],
    reason: "中秋短假不适合把时间耗在路上，厦门、福冈和台北兼顾海滨、人文与较短航程，直飞和中转价差值得观察。",
    priority: 82,
    enabled: true
  },
  {
    id: "preset-national-day-kansai-korea",
    name: "国庆东亚人文与城市线",
    holidayId: "national-day-2026",
    destinationIds: ["osaka-kyoto", "tokyo", "seoul"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 2600,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct", "transfer"],
    tags: ["历史人文", "短中程国际", "价格波动"],
    reason: "东亚航线从上海出发班次多，历史人文匹配度高，直飞和中转价格差值得分开监控。",
    priority: 96,
    enabled: true
  },
  {
    id: "preset-spring-warm-island",
    name: "春节避寒海岛与东南亚线",
    holidayId: "spring-festival-2027",
    destinationIds: ["sanya", "bangkok", "danang", "chiang-mai"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 3200,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct", "transfer"],
    tags: ["避寒", "自然风景", "性价比"],
    reason: "春节适合温暖目的地，但价格涨幅大，提前监控能更早捕捉低价窗口。",
    priority: 100,
    enabled: true
  },
  {
    id: "preset-labor-domestic-nature",
    name: "五一国内自然与古城线",
    holidayId: "labor-day-2027",
    destinationIds: ["guilin", "lijiang-dali", "xian"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 1900,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct", "transfer"],
    tags: ["自然风景", "历史人文", "国内长线"],
    reason: "五天假期适合国内长线，桂林、云南、西安分别覆盖自然山水和历史人文。",
    priority: 90,
    enabled: true
  },
  {
    id: "preset-new-year-short-direct",
    name: "元旦近程直飞轻旅行",
    holidayId: "new-year-2027",
    destinationIds: ["beijing", "xian", "seoul"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 1700,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct"],
    tags: ["短假", "直飞", "人文"],
    reason: "短假优先减少路上时间，推荐直飞多、三天可成行的目的地。",
    priority: 80,
    enabled: true
  },
  {
    id: "preset-winter-snow-hot-spring",
    name: "春节雪景温泉线",
    holidayId: "spring-festival-2027",
    destinationIds: ["sapporo", "tokyo", "lijiang-dali"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 3600,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct", "transfer"],
    tags: ["雪景", "温泉", "自然风景"],
    reason: "冬季风景辨识度强，札幌和东京周边温泉适合中转比价，云南适合国内替代方案。",
    priority: 86,
    enabled: true
  },
  {
    id: "preset-qingming-short-culture",
    name: "清明短假人文与海滨线",
    holidayId: "qingming-2027",
    destinationIds: ["xiamen", "hong-kong", "taipei"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 1800,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct"],
    tags: ["短假", "海滨", "人文"],
    reason: "清明假期时间短，优先选择直飞密度高、城市体验集中的目的地。",
    priority: 78,
    enabled: true
  },
  {
    id: "preset-dragon-boat-coastal",
    name: "端午海滨与近程国际线",
    holidayId: "dragon-boat-2027",
    destinationIds: ["xiamen", "fukuoka", "seoul"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 2100,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct", "transfer"],
    tags: ["短假", "直飞", "美食"],
    reason: "端午适合少请假出行，厦门、福冈和首尔都能控制路上时间。",
    priority: 76,
    enabled: true
  },
  {
    id: "preset-labor-mountain-city",
    name: "五一山水与美食城市线",
    holidayId: "labor-day-2027",
    destinationIds: ["chengdu", "zhangjiajie", "xiamen"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 1900,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct", "transfer"],
    tags: ["自然风景", "美食", "国内"],
    reason: "五一适合国内中程旅行，山水、城市和海滨三类体验可以按价格灵活取舍。",
    priority: 84,
    enabled: true
  },
  {
    id: "preset-national-day-domestic-far",
    name: "国庆国内长线自然线",
    holidayId: "national-day-2026",
    destinationIds: ["lijiang-dali", "zhangjiajie", "chengdu"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 2400,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct", "transfer"],
    tags: ["长假", "自然风景", "国内长线"],
    reason: "国庆长假适合把自然目的地纳入池子，直飞和中转价格差需要分开观察。",
    priority: 87,
    enabled: true
  },
  {
    id: "preset-spring-southeast-asia-culture",
    name: "春节东南亚人文性价比线",
    holidayId: "spring-festival-2027",
    destinationIds: ["hanoi", "penang", "singapore"],
    originCity: "上海",
    originAirportCodes: ["PVG", "SHA"],
    tripType: "round",
    recommendedBudgetAmount: 3400,
    recommendedBudgetCurrency: "CNY",
    recommendedStrategyTypes: ["direct", "transfer"],
    tags: ["春节", "历史人文", "性价比"],
    reason: "春节东南亚需求高但价差大，河内、槟城和新加坡适合按预算与中转容忍度比较。",
    priority: 85,
    enabled: true
  }
];
